; 加载规则集
ruleset=➡️国内,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/China/China.list
ruleset=🌍国外,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Global/Global.list

; ⚡url‑test‑最低延迟：网页浏览自动选延迟最优，连续4次失败判定失效，lazy=true空闲不探测
custom_proxy_group=⚡url‑test‑最低延迟`url-test`.*`https://cp.cloudflare.com/generate_204`120,4,4000,200,lazy=true

; 🚀fallback‑优先代理 追剧长视频，只有节点彻底失效才切换，减少抖动
custom_proxy_group=🚀fallback‑优先代理`fallback`.*`[]DIRECT`https://cp.cloudflare.com/generate_204`300,4,4000,lazy=true

; ✋手动‑全部：手动单点测试节点
custom_proxy_group=✋手动‑全部`select`.*

; 主策略组🌍国外，一键切换两种自动模式 / 手动 / 直连 / 拒绝
custom_proxy_group=🌍国外`select`[]⚡url‑test‑最低延迟`[]🚀fallback‑优先代理`[]✋手动‑全部`[]DIRECT`[]REJECT
; ➡️国内策略组，国内流量默认直连
custom_proxy_group=➡️国内`select`[]DIRECT`[]REJECT

; =========核心开关=========
enable_rule_generator=false
overwrite_original_rules=true

; =========后置自定义规则【从上往下匹配，顺序不能乱】=========
# 1.最高优先级：拦截STUN，防止ping0.cc WebRTC泄露真实IP
- AND,(NETWORK,UDP),(DST-PORT,3478),REJECT-DROP
- AND,(NETWORK,UDP),(DST-PORT,5349),REJECT-DROP
# 2.局域网保留直连，访问软路由/NAS不进代理
- IP-CIDR,192.168.0.0/16,DIRECT,no-resolve
- IP-CIDR,10.0.0.0/8,DIRECT,no-resolve
- IP-CIDR,172.16.0.0/12,DIRECT,no-resolve

# 3.国内域名IP走国内策略组（优先直连）
- RULE-SET,➡️国内,➡️国内
# 4.国外域名IP走🌍国外主策略组（自动组）
- RULE-SET,🌍国外,🌍国外
# 5.兜底：所有未匹配流量交给🌍国外
- MATCH,*,🌍国外
